[package]
name = "gll-macros"
version = "0.1.0"
authors = [
    "Ana-Maria <mihalacheana.maria@yahoo.com>",
    "Eduard-Mihai Burtescu <edy.burt@gmail.com>"
]
repository = "https://github.com/lykenware/lyken"
license = "MIT/Apache-2.0"
description = "Macros used with the gll crate."

[dependencies]
gll = { path = ".." }

[lib]
doctest = false
proc-macro = true
